# Generated by Django 2.0.5 on 2019-03-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Book',
        ),
    ]
